all:
  children:
    # Purple Kali VM - Security Operations Orchestrator
    orchestrators:
      hosts:
        purple-kali:
          ansible_host: 192.168.1.100          # Purple Kali VM IP address
          ansible_user: kali                    # SSH username for Purple Kali
          ansible_python_interpreter: /usr/bin/python3  # Python path on target
          log_file: purple-kali.log            # Corresponding static log file name
          
          # Your existing script paths on Purple Kali VM
          wrapper_script: "/home/kali/lynis_automation/wrapper_lynis.sh"
          main_script: "/home/kali/lynis_automation/automated_lynis.sh"
          target_list: "/home/kali/lynis_automation/list.txt"
          reports_base_dir: "/home/kali/lynis_automation/reports"

  vars:
    # Global SSH configuration for all hosts
    ansible_ssh_private_key_file: ~/.ssh/soc_automation
    # Timestamp variable for consistent logging across all tasks
    scan_timestamp: "{{ ansible_date_time.iso8601 }}"
    # Local directory on Blue Kali for static log files (ELK integration)
    local_logs_dir: "~/elk-stack/logs"
